### ISSUE TITLE
seems not to work in a multiple server environment

### ISSUE THREAD

**Issue by MisterButcher** [em92/dynamicip#1]
Hello, when there are more than 1 quake live servers on the same machine, the first server running the update script will recognize the ip change and update the ip address on qlstats for his port. after that, the database is updated and old ip is overwritten with current ip.
if now the second server runs the script, old ip is equal to current ip and therefore no update happens for the second server on qlstats.
The db key (MYIP_KEY) should somehow be server-dependent, e.g. by adding the port number. As i have not python skills i am not able to implement it on my own.
Cheers, Butcher

**Comment by em92** [comment]
Fixed in https://github.com/em92/dynamicip/commit/0e8851527f18d850c074748456f7ab795f53f124
Updating all ports at once
Thank you for the issue.
