### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by friz72** [em92/dynamicip#2]
С 02.06 сервер начал виснуть при попытке загрузить твой плагин. В чем может быть проблема?

**Comment by em92** [comment]
Предполагается, что сервер будет на короткое время виснуть при загрузке плагина (идет запрос на получение списка серверов с админ панели). Т.е. такой эффект наблюдается только один раз, до перезапуска самого сервера, или же после ручного перезапуска плагина.

Если сервер вообще не отвисает, то это странно. Если это так, то требуется узнать, что выводят эти команды:
`curl http://qlstats.net:8083/api/servers -v -o /tmp/1.tmp`
`nmap qlstats.net -p 8081-8084,80`

**Comment by friz72** [comment]
При запуске самого сервера, он зависает на загрузке плагина dynamicip и не запускается. Последняя попытка дала 6 часов ожидания запуска сервера. Запустить сервер удалось только при удалении из server.cfg плагина. При ручной загрузке плагина сервер зависает при нажатии всеми участниками клавиши f3.

Starting Nmap 6.47 ( http://nmap.org ) at 2017-06-05 16:56 YEKT
Stats: 0:00:01 elapsed; 0 hosts completed (0 up), 1 undergoing Ping Scan
Ping Scan Timing: About 50.00% done; ETC: 16:56 (0:00:01 remaining)
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.15 seconds

Я так понимаю, что-то поменялось у qlstats.net и в результате плагин не может соединиться и зависает весь сервер

**Comment by friz72** [comment]
Starting Nmap 6.47 ( http://nmap.org ) at 2017-06-05 16:56 YEKT
Stats: 0:00:01 elapsed; 0 hosts completed (0 up), 1 undergoing Ping Scan
Ping Scan Timing: About 50.00% done; ETC: 16:56 (0:00:01 remaining)
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.15 seconds

**Comment by em92** [comment]
>При ручной загрузке плагина сервер зависает при нажатии всеми участниками клавиши f3.

Такое я уже исправлял в коммите https://github.com/em92/dynamicip/commit/8f1c7568d8436a22154cfeb2bccf0a76c34b62d1. Теперь должно зависать только один раз при загрузке плагина.

А если вызвать это?
`nmap qlstats.net -p 8081-8084,80 -Pn`
И что там с этим:
`curl http://qlstats.net:8083/api/servers -v -o /tmp/1.tmp`

**Comment by friz72** [comment]
Зависает сервер насмерть просто при попытке загрузить плагин. Сделал !load dynamicip и сервер завис.


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*                           Trying 213.32.64.71...
* TCP_NODELAY set
  0     0    0     0    0     0      0      0 --:--:--  0:00:32 --:--:--     0^C


Starting Nmap 6.47 ( http://nmap.org ) at 2017-06-05 18:04 YEKT
Nmap scan report for qlstats.net (213.32.64.71)
Host is up.
PORT     STATE    SERVICE
80/tcp   filtered http
8081/tcp filtered blackice-icecap
8082/tcp filtered blackice-alerts
8083/tcp filtered us-srv
8084/tcp filtered unknown

Nmap done: 1 IP address (1 host up) scanned in 3.22 seconds

**Comment by em92** [comment]
Судя по всему, владелец qlstats.net блокирует входящие пакеты с твоего IP-шника и твоих соседей из диапазона. Сообщи ему об этом и поясни, что ты используешь вот такой плагин, который при смене ip-адреса обращается к админ-панеле и выставляет новый ip-шник.

После того, как он снимет блокировку, то после `nmap qlstats.net -p 8081-8084,80` будет примерно вот такое:
```nmap qlstats.net -p 8081-8084,80

Starting Nmap 6.40 ( http://nmap.org ) at 2017-06-05 18:15 +05
Nmap scan report for qlstats.net (213.32.64.71)
Host is up (0.015s latency).
PORT     STATE SERVICE
80/tcp   open  http
8081/tcp open  blackice-icecap
8082/tcp open  blackice-alerts
8083/tcp open  us-srv
8084/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.10 seconds```
И соответственно плагин заработает, как прежде.
