### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jeromim** [em92/dynamicip#3]
is the plugin working? I am running and not registering on the qlstats website. would appreciate the help. thanks

**Comment by em92** [comment]
What does qlds console show?

**Comment by jeromim** [comment]
[minqlx.load_plugin] INFO: Loading plugin 'dynamicip'...
[minqlx.dynamicip.__init__] INFO: zmq_password: ****
[minqlx.dynamicip.__init__] INFO: zmq_port: 27960
[minqlx.dynamicip.__init__] INFO: server_owner: 76561198029829058
[minqlx.dynamicip.__init__] INFO: current_ip: 191.54.190.241
pedreiro^7: !load dynamicip
Hitch warning: 2103 msec frame time
broadcast: print "Plugin ^6dynamicip ^7has been successfully loaded.\n"\n\n

I have to enter the game and load the plug! load dynamicip, because the plug does not automatically load on server.cfg. I enter qlstats does not register.

**Comment by em92** [comment]
I will check later, what is going on over there. Meanwhile:
1. Make sure, you added this plugin to qlx_plugins cvar.
2. What value did you set to qlx_qlStatsAdminPanel?

**Comment by jeromim** [comment]
set qlx_qlStatsAdminPanel "qlstats.net/panel3"

I tested all the panels. 1, 2, 3 and 4.

I also tried to edit the dynamicip.py file and changed http to https and it didn't work.

self.api_url = "http://{}/api/".format(self.get_cvar("qlx_qlStatsAdminPanel"))

**Comment by em92** [comment]
Btw, AFAIK it registers in qlstats.net when game starts. Try to add bot or invite someone and start the game

**Comment by em92** [comment]
But in any case, it is assumed that you register manually first, then plugin will update ip automatically

**Comment by jeromim** [comment]
thanks for the help, i managed to make it functional.

however, you need to change from http to https
self.api_url = "http://{}/api/".format(self.get_cvar("qlx_qlStatsAdminPanel"))

http did not work, I switched to https it worked. it may be necessary to fix your plugin for the staff not to face this problem.

**Comment by em92** [comment]
Thank you!
