### ISSUE TITLE
Get Public IP and zmq not working

### ISSUE THREAD

**Issue by philipecella** [em92/dynamicip#4]
Hey, thanks for your plugin!

I had to modify 2 things to get it to work

Here what i've changed:

`self.zmq_port = self.get_cvar("zmq_stats_port")
if self.zmq_port == "" or self.zmq_port is None:
    self.zmq_port = self.get_cvar("net_port")
    if self.zmq_port == "" or self.zmq_port is None:
        self.zmq_port = "27960"
else:
    self.zmq_port = str(self.zmq_port)
`

and the 2nd part was about to get public IP

the website is not working anymore, so i put this one:

`def get_current_ip(self):
    try:
        return requests.get("https://ifconfig.me/ip").text
    except Exception as e:
        self.logger.warning(f"Failed to get public IP: {e}")
        return "127.0.0.1"
`

hope it works for someone who needs this.

**Comment by em92** [comment]
Thank you!
